name: scada
services:
  # FastAPI Backend Service
  api:
    container_name: scada-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - zxnet
    expose:
      - "8080"
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      
      # Supabase Auth Configuration
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_JWT_SECRET: ${JWT_SECRET}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      
      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS}
      
      # Environment
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DEBUG: ${DEBUG:-true}
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/__pycache__

  # Frontend UI Service
  ui:
    container_name: scada-ui
    build:
      context: ../kmfscada-ui
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - zxnet
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL:-http://localhost:8080}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY:-your-anon-key}
      NEXT_PUBLIC_API_URL: ${API_URL:-http://localhost:8080}
    depends_on:
      kong:
        condition: service_started
      api:
        condition: service_started

networks:
  zxnet:
    external: true